---
- hosts: 172.31.39.137
  become: yes
  tasks:
  - name: i want execute linux command
    command: hostname -f
    register: myfirsttaskresult
  
  - name: i want to disply my first task result
    debug:
       msg: "{{myfirsttaskresult}}"


  - name: install git
    apt:
      name: git
      state: present
    when: myfirsttaskresult.stderr ==""

  - name: install tree
    apt:
       name: tree
       state: present
    when: myfirsttaskresult.stderr !=""

   
