---
- hosts: 172.31.39.137
  become: yes
  tasks:
  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget

  - name: install tree
    apt:
      name: tree
      state: present
    tags: mytree

  - name: install git
    apt:
      name: git
      state: present
    tags: mygit
   